version: "3.3"

services:
  data1:
    image: mongo:3.4
    networks:
      - ds-cluster
    volumes:
      - /nfs/data/mongo/data1:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      placement:
        constraints:
          - node.hostname == node1

  data2:
    image: mongo:3.4
    networks:
      - ds-cluster
    volumes:
      - /nfs/data/mongo/data2:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      placement:
        constraints:
          - node.hostname == node2

  data3:
    image: mongo:3.4
    networks:
      - ds-cluster
    volumes:
      - /nfs/data/mongo/data3:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      placement:
        constraints:
          - node.hostname == node3

  cfg1:
    image: mongo:3.4
    networks:
      - ds-cluster
    volumes:
      - /nfs/data/mongo/cfg1:/data/configdb
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    deploy:
      placement:
        constraints:
          - node.hostname == node1

  cfg2:
    image: mongo:3.4
    networks:
      - ds-cluster
    volumes:
      - /nfs/data/mongo/cfg2:/data/configdb
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    deploy:
      placement:
        constraints:
          - node.hostname == node2

  cfg3:
    image: mongo:3.4
    networks:
      - ds-cluster
    volumes:
      - /nfs/data/mongo/cfg3:/data/configdb
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    deploy:
      placement:
        constraints:
          - node.hostname == node3

  mongos1:
    image: mongo:3.4
    networks:
      - ds-cluster
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    deploy:
      placement:
        constraints:
          - node.hostname == node1

  mongos2:
    image: mongo:3.4
    networks:
      - ds-cluster
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    deploy:
      placement:
        constraints:
          - node.hostname == node2

  bootstrap:
    image: stefanprodan/mongo-bootstrap:latest
    networks:
      - ds-cluster
    command:
      - '-dataSet=datars/data1:27017,data2:27017,data3:27017'
      - '-configSet=cfgrs/cfg1:27017,cfg2:27017,cfg3:27017'
      - '-mongos=mongos1:27017,mongos2:27017'
  
networks:
  ds-cluster:
    external: true

