version: '3.3'
services:
  rater:
    image: registry-vpc.cn-hongkong.aliyuncs.com/dynamicheart/rater
    environment:
      RATER_ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
      RATER_RUN_TIME: 15
    networks:
     - ds-cluster

networks:
  ds-cluster:
    external: true

